### ISSUE TITLE
fold Data.Semigroup.Generic into base

### ISSUE THREAD

**Issue by chessai** [ekmett/semigroups#100]
@ekmett @RyanGlScott what are your thoughts on this? Other than annoying operational bits, I think the module would fit right in in base.

**Comment by chessai** [comment]
Of course we'd probably need Data.Monoid.Generic or something like that (an example of an annoying operational bit)

**Comment by RyanGlScott** [comment]
I'm not exactly sure what is being proposed. Can you describe in greater detail which parts of `Data.Semigroup.Generic` will be migrated to which modules in `base`?

**Comment by phadej** [comment]
`base` has `Generically` now, so `Semigroup` can be derived via it generically. There isn't `genericMappend` though available standalone AFAIK.

**Comment by phadej** [comment]
I'd close this issue, as it is not actionable anyway. It's up to people to propose to CLC additions or changes to `base`.

**Comment by RyanGlScott** [comment]
I agree with https://github.com/ekmett/semigroups/issues/100#issuecomment-1221512896. Closing.
