### ISSUE TITLE
transformers-0.6 on old GHC

### ISSUE THREAD

**Issue by phadej** [ekmett/semigroups#101]
```
diff --git a/semigroups.cabal b/semigroups.cabal
index 37daad7..566470d 100644
--- a/semigroups.cabal
+++ b/semigroups.cabal
@@ -178,7 +178,7 @@ library
       build-depends: unordered-containers >= 0.2  && < 0.3
 
     if flag(transformers)
-      build-depends: transformers        >= 0.2 && < 0.6
+      build-depends: transformers        >= 0.2 && < 0.7
                    , transformers-compat >= 0.5 && < 1
 
```

Seems to compile fine. (The up/downside is that it will make more install plans for older GHCs)

In a way you can decide that `transformers-0.6` and pre GHC-8 are not a good idea and practically prevent that by not relaxing this bound.

Therefore I'm not relaxing it myself.

**Comment by RyanGlScott** [comment]
I've relaxed the version bounds in e30bcdbb1e7f153b0ed7d4d3ed40e353ad10fccc.

**Comment by phadej** [comment]
Thanks!
