### ISSUE TITLE
I ended up writing these when using semigroups

### ISSUE THREAD

**Issue by gregwebs** [ekmett/semigroups#16]
Interested in putting any of these into the package?

- [x] length ∷ NonEmpty a → Int
- [x] transpose ∷ NonEmpty (NonEmpty a) → NonEmpty (NonEmpty a)
- [x] sortWith :: Ord o => (a -> o) -> NonEmpty a -> NonEmpty a

More obscure
- [ ] splitAt1 ∷ NonEmpty a → (a, [a])
- [ ] fromPair :: (a,a) -> NonEmpty a
- [ ] neighboringJusts :: [Maybe a] -> [NonEmpty a]

**Comment by ekmett** [comment]
Closed by #18.
