### ISSUE TITLE
Enrich semigroup with left zeros

### ISSUE THREAD

**Issue by feuerbach** [ekmett/semigroups#25]
I'd like to see a wrapper for Either whose Semigroup/Monoid instances would work like the standard Either instance, except Lefts would be combined using the underlying semigroup operation.

I can prepare a patch if needed.

Some issues to discuss:

* naming. `WithLeftZeros` sounds too verbose.
* I think wrapping left zeros in `Left`, not `Right`, is more intuitive because of both the pun and the intuition from the Applicative instance. But that'd be inconsistent with the provided `Either` instance
* because of short-cicuiting, it is unlikely that strictness analysis will tell to evaluate underlying `<>` eagerly, which can lead to memory leaks. Should there be a strict and non-strict versions of the wrapper? Or perhaps only add the strict one? I understand it's unconventional, but it'll probably do the right thing most of the time, and such behavior is easier to override than the opposite

**Comment by ekmett** [comment]
I think I'm going to relegate that to `validation`, `either`, or a related package. There are enough points in the design space, and I'm trying to keep this package limited in scope to easily standardized bits and pieces.
