### ISSUE TITLE
I really want NFData and Storable instances!

### ISSUE THREAD

**Issue by nanonaren** [ekmett/semigroups#33]
I don't about you guys but I often need to add NFData and Storable instances myself for the monoids like Sum, Product, All, etc for using them with Data.Vector.Storable and writing strict folds! Would this be the right package to add this? Is there some reason Storable instances are not defined?

**Comment by ekmett** [comment]
This package already supplies NFData instances for everything it supplies. If it doesn't, please reopen this issue.

`deepseq` now supplies instance for `Data.Monoid`.

So this looks done.
