### ISSUE TITLE
Option (First a) how does it work?

### ISSUE THREAD

**Issue by MarkZander** [ekmett/semigroups#50]
In semigroup documentation:

-- | Use @'Option' ('First' a)@ to get the behavior of 'Data.Monoid.First' from @Data.Monoid@.

In my code:

stats1 :: TempTime -> Option (First LocalTime)
stats1 tt@(Arg temp time) = Option (First time)

Error message:

    Couldn't match expected type ‘Maybe (First LocalTime)’
                with actual type ‘First LocalTime’
    In the first argument of ‘Option’, namely ‘(First time)’
    In the expression: Option (First time)

Is there a more thorough example of how to use this feature?

Thanks, Mark

**Comment by ekmett** [comment]
(Option (Just (First time)))

The Option data constructor is just a wrapper around Maybe.

**Comment by MarkZander** [comment]
Thanks, it works now. I was just missing the Just data constructor. Somehow I wasn’t putting it together, even with the compiler error messages.

Option of course just hides Maybe to the instances.

I see the direction you have taken this now. You are taking semigroups and wrapping them in Option in order to extend them into Monoids. So First is a semigoup and Option First is a monoid.

Thanks for you explanations. It just took a while to get through.

One further question, could Min and Option be used for a minimum Integer?

Mark

**Comment by ekmett** [comment]
`Option (Max Integer)` gives you `Option Nothing` acting as a `-Infinity`, as it has to be a unit for `Option (Max Integer)`.

Similarly, `Option (Min Integer)` gives you `Option Nothing` acting as `Infinity`.

**Comment by MarkZander** [comment]
Thanks, I realized that after looking at the code after your previous emails. Previous to that I wondered which method would be used, using maybe or using bounds. I can now see that both options are available by the way you put things together.

I got confused over leaving out the maybe constructor (Just). The Min type for Integer leaves out Maybe but the constructor requires Just. Somehow I couldn’t put that together:

minInteger :: Integer -> Option (Min Intgeger)
minInteger i = Option $ Just $ Min Integer

or

minInteger = Option . Just . Min

I thought the following would be useful for brevity:

oJust :: a -> Option a
oJust = Option . Just

oNothing :: Option a
oNothing = Option $ Nothing

I wrote 3 orphaned instances. Bounded Float, Bounded Double and a Monoid for a six tuple. Haskell libraries could really use a more complete floating point. Constants like nan, infinity and negative infinity don’t seem defined.

I should probably post my code as an example for others to shoot at.

Thanks for all of your help. The semigroup library really made for short code even if it did take me a while to figure out what was going on.

Mark

**Comment by ekmett** [comment]
Ultimately the reason why we don't have a `Bounded Float` is that NaN messes everything up.

```haskell
(0/0) <= (1/0::Float) = False
```

so `inf = 1/0` is not `maxBound` for `Float`.

Similarly

```haskell
(-1/0::Float) <= (0/0) = False
```

so `-inf` is not `minBound`.

This is why these instances are not and cannot be standard.

**Comment by MarkZander** [comment]
I’ll have None of that!

inf is not maxBound either.

I guess Option (Min Float) is the only option then.

Mark

**Comment by MarkZander** [comment]
Prelude> 0/0 <= 0
False
Prelude> 0/0 >= 0
False

Looks like floats aren’t ordered in the presence of NaN.

Mark

**Comment by ekmett** [comment]
Correct. Haskell complies with IEEE on the behavior of NaN at the expense of being able to reason about `Ord` as an actual total ordering.

**Comment by MarkZander** [comment]
I’ve always wondered if someone would step up to the challenge of defining operations of floats that are efficient and yet obey the algebraic laws in some way. I’m not holding my breath.

Best as I can tell NaN is the IEEE equivalent of _|_

Mark
