### ISSUE TITLE
Replace `times1p` with `stimes`.

### ISSUE THREAD

**Issue by ekmett** [ekmett/semigroups#54]
We should replace `times1p`. The naming convention of it doesn't adapt well to `Data.Monoid` and standardization.

If we added `stimes` instead which would be allowed to fail on 0 or less, then we can add `mtimes` to `Monoid`, which can delegate to `stimes` on 1+ by default and `mempty` on 0. This avoids the minor addition/subtraction dance we have to play if we want such a combinator today, and makes the naming much more homogeneous.

**Comment by hvr** [comment]
Fwiw, A quick `rgrep` for `stimes` over 8000+ Hackage packages seems to
indicate that symbol is effectively unused (no match found).

`mtimes` has a few hits but still negligible (mostly because it's common
abbrevation of modification-time):


    $ rgrep --include '*.*hs*' --include '*.[xy]' '[^A-Za-z_]mtimes'  srcs/ 
    srcs/git-annex-5.20150528/Remote/Helper/Git.hs:	mtimes <- liftIO $ mapM (modificationTime <$$> getFileStatus)
    srcs/git-annex-5.20150528/Remote/Helper/Git.hs:	let lastsynctime = case mtimes of
    srcs/git-annex-5.20150528/Remote/Helper/Git.hs:		_ -> show $ posixSecondsToUTCTime $ realToFrac $ maximum mtimes
    srcs/git-annex-5.20150528/Assistant/Threads/SanityChecker.hs: - mtimes. So, this should only be called from the
    srcs/git-annex-5.20150528/Utility/InodeCache.hs: - The weak mtime comparison treats any mtimes that are within 2 seconds
    srcs/git-annex-5.20150528/Logs/Unused.hs:		(Just int, Just key, mtimestamp) -> Just (key, (int, mtimestamp))
    srcs/kontrakcja-templates-0.1/src/Text/StringTemplates/Utils.hs:  mtimes <- mapM getModificationTime $ dirs ++ files
    srcs/kontrakcja-templates-0.1/src/Text/StringTemplates/Utils.hs:  return $ maximum mtimes
    srcs/rounding-0.3.0/Numeric/Rounding.hsc:        , ptimes = mtimes
    srcs/rounding-0.3.0/Numeric/Rounding.hsc:        , ptimes = mtimesf
    srcs/rounding-0.3.0/Numeric/Rounding.hsc:foreign import ccall unsafe "rounding.h mtimes"
    srcs/rounding-0.3.0/Numeric/Rounding.hsc:    mtimes :: CInt -> CDouble -> CDouble -> CDouble 
    srcs/rounding-0.3.0/Numeric/Rounding.hsc:foreign import ccall unsafe "rounding.h mtimesf"
    srcs/rounding-0.3.0/Numeric/Rounding.hsc:    mtimesf :: CInt -> CFloat -> CFloat -> CFloat 
    srcs/shake-0.15.2/src/Test/Type.hs:    mtimes <- forM [1..10] $ \i -> fmap fst $ duration $ do
    srcs/shake-0.15.2/src/Test/Type.hs:    putStrLn $ "Longest file modification time lag was " ++ show (ceiling (maximum mtimes * 1000)) ++ "ms"
    srcs/shake-0.15.2/src/Test/Type.hs:    return $ sleep $ min 1 $ maximum mtimes * 2
    srcs/simplex-0.3.8/src/simplex.hs:    mtimes1 <- mapM getModificationTime files
    srcs/simplex-0.3.8/src/simplex.hs:    mtimes2 <- mapM (getModificationTime' . flip addExtension ext . dropExtension) files
    srcs/simplex-0.3.8/src/simplex.hs:    let files' = zip3 files mtimes1 mtimes2
    srcs/yesod-static-1.5.0/Yesod/Static.hs:          mtimes <- readIORef mtimeVar
    srcs/yesod-static-1.5.0/Yesod/Static.hs:          oldt <- case M.lookup f mtimes of
    srcs/yesod-static-1.5.0/Yesod/Static.hs:            Nothing -> writeIORef mtimeVar (M.insert f newt mtimes) >> return newt

**Comment by ekmett** [comment]
bb03b9365a adds most of this. I'll clean it up and ship it out.
