### ISSUE TITLE
Add `Data.Text.NonEmpty` module

### ISSUE THREAD

**Issue by jdnavarro** [ekmett/semigroups#55]
I'm considering sending a PR myself, but since this is a bit laborious I'd like to know first if this would be a welcome addition.

My need comes from trying to fulfill `Prim`s laws when dealing with serialization/deserialization of `Map`s with `Text` keys. The empty key is the offender and wouldn't like to support this case anyway since it doesn't make sense to allow it at all.

I could also take care of `ByteString` and the corresponding Lazy variants at the same time.

**Comment by ekmett** [comment]
This package is migrating into `base` in 8.0, so there won't be anything here really to accept such a patch.

It probably just belongs in a small package of its own.

**Comment by ekmett** [comment]
I'm missing something about why the empty key is problematic for you.

**Comment by ekmett** [comment]
Internally a Text is

```haskell
data Text = Text {-# UNPACK #-}!Array {-# UNPACK #-}!Int {-# UNPACK #-}!Int
```

There isn't anything fancy about the empty `Text`, other than a choice of sentinel array.

**Comment by jdnavarro** [comment]
I just realized after writing the whole explanation that there are other ways to break the `Prism` laws even if I had non-empty `Text`. I'm leaving the original explanation below in case you have suggestions.

--------

I'm dealing with a `Prism` of the type `Prism' Text `[`MultiMap`](https://github.com/plutonbrb/nero/blob/master/src/Nero/Param.hs#L60). I can change the internal representation of `MultiMap` if necessary, but the idea is to be able to serialize/deserialize the a URL *querystring*. Here is a convoluted example in pseudo-syntax:

This `Text`:
`query&query&query=value&query2=&query3=value3`

Parses to this:
`{ query: [Nothing, Nothing, Just "value"], query2: [Just ""], query3: [Just "value3"] }`

However these 2 `MultiMap`s break the laws when rendering:

`{}` -> `""`
`{ "": Nothing }` -> `""` `-- I'm not expecting this case in a real scenario anyway`

I don't have this problem with the `Values` because I'm using `NonEmpty` instead of a `List`, but there is no equivalent for the `query`s.

Right now I'm handling this with an *ad-hoc* `Text` wrapper and a smart constructor that requires at least one `Char`. It's good enough for me in the short-term, but I was wondering if it's worth going all the way in and try to make the *non-empty* `Text`/`ByteString` a more *official* type.
