### ISSUE TITLE
Update semigroups package to post-GHC8 situation

### ISSUE THREAD

**Issue by hvr** [ekmett/semigroups#56]
(more context: https://prime.haskell.org/wiki/Libraries/Proposals/SemigroupMonoid)

This involves several sub-items:

- [x] make `semigroups` conditionally hide `Data.Semigroup` and `Data.List.NonEmpty`
- [x] add `base < 4.9` upper bound to released `semigroups` versions on Hackage to mark `semigroups` as incompatible w/ GHC8's `base`

as well as (conditionally) move instances and add `base < 4.9` where needed to

- [x] `bytestring`
- [x] `containers`
- [x] `deepseq`
- [x] `tagged`
- [x] `text`
- [x] `hashable`
- [x] `unordered-containers`

After this, for GHC>=8, `semigroups` will only provide `Data.Semigroup.Generic`

**Comment by DanBurton** [comment]
:+1: came here to request the same.

**Comment by hvr** [comment]
The checkboxes are not yet ticked off, so I don't think this ticket is ready to be closed

**Comment by hvr** [comment]
@ekmett I think we need to retroactively add `base < 4.9` upper bounds to all past releases of packages which `semigroups` provided instances for in the past to make this work properly.

**Comment by ekmett** [comment]
Sure.

**Comment by hvr** [comment]
Fyi, when trying to make `binary` depend on `semigroups` for older GHC for https://github.com/kolmodin/binary/pull/96 I couldn't due to package dep cycles forcing me to use CPP :-/

**Comment by RyanGlScott** [comment]
Is there anything else that needs to be done for this to be resolved?

**Comment by ekmett** [comment]
I think we're good.
