### ISSUE TITLE
Intersection-y Semigroups

### ISSUE THREAD

**Issue by exergasia** [ekmett/semigroups#59]
Data.{Map, Set, HashMap, HashSet, etc} have `(<>)` as a union-y operation But they're also a semigroup under intersection, and it'd be nice to offer a generic way to select an intersection-y instance. Note that, for finite containers, there's not a sensible identity element for intersections, so this can't also be a Monoid.

Sketch of what that would look like:

```
class Intersectable s where
  intersection :: s -> s -> s

instance (Ord k) => Intersectable (Data.Map.Map k v) where
  intersection = Data.Map.intersection

--etc

newtype Intersection s = Intersection { getIntersection :: s }
  deriving (Show, Read) --etc

instance (Intersectable s) => Semigroup (Intersection s) where
  Intersection a <> Intersection b = Intersection (intersection a b)
```

Names are subject to bikeshedding, of course. Data.List exports `intersect` and containers/unordered-containers use `intersection` so I suggest preferring `intersection` on the assumption that containters and unordered-containers are generally imported qualified.

Whether to specify which side the elements in the result come from is a question: either always left (containers and unordered-containers do that) or caveat emptor are the options here.

**Comment by ekmett** [comment]
Given that this package is basically being absorbed into base as is, and that the merge has already happened. I think these probably belong in another package.

My reducers package used to supply something like this for unions:

http://hackage.haskell.org/package/reducers-3.12.1/docs/Data-Semigroup-Union.html

**Comment by ekmett** [comment]
Closing as out of scope as this package is now going to basically just track base changes.
