### ISSUE TITLE
Documentation bug in Data.List.NonEmpty.cycle

### ISSUE THREAD

**Issue by audunska** [ekmett/semigroups#60]
The documentation for cycle says that
> cycle [1,2,3] = 1 :| [2,3,1,2,3,...]

But the argument should be NonEmpty, so it should read

> cycle (1 :| [2,3]) = 1 :| [2,3,1,2,3,...]

**Comment by audunska** [comment]
Also filed against ghc as #11178:
https://ghc.haskell.org/trac/ghc/ticket/11178

**Comment by RyanGlScott** [comment]
It looks like [Trac #11178](https://ghc.haskell.org/trac/ghc/ticket/11178) was fixed in `base`. Do you mind submitting a pull request which implements the [same changes](https://git.haskell.org/ghc.git/commitdiff/758e6b3a935242acacfa5f1c23ecd1b0e9310e28)?
