### ISSUE TITLE
foldl1 for NonEmpty

### ISSUE THREAD

**Issue by andrewthad** [ekmett/semigroups#61]
I think that it would be good to add `foldl1` to `NonEmpty`, especially because we can actually write a safe version of it:

    nonEmptyFoldl1 :: (a -> a -> a) -> NonEmpty a -> a
    nonEmptyFoldl1 g (a :| as) = List.foldl g a as

The same can be done for `foldr1`. Although at this point in time, it may make more sense to add this to `base-4.9` instead of `semigroups`.

**Comment by andrewthad** [comment]
Also, having `append` would be nice.

**Comment by tomjaguarpaw** [comment]
+1 I've just noticed that `append` is missing, too.

**Comment by RyanGlScott** [comment]
Are `Data.Foldable.{foldl1,foldr1}` and `Data.Semigroup.<>` not sufficient?

**Comment by tomjaguarpaw** [comment]
I thought there'd be a catch!  Yes, they're sufficient but should be documented as such.  Having no reference to "append" in the Haddock is somewhat disconcerting.

**Comment by RyanGlScott** [comment]
That sounds reasonable. But since `Data.List.NonEmpty` is in `base` now, make sure any changes to its documentation also get merged into `base` as well.

**Comment by ekmett** [comment]
Any changes here will be made to simply track base. As a result if you want such a function I recommend you file it as a proposal to libraries@haskell.org, so we can get it into base. We'll shadow any changes made to base will be mirrored here for older GHC versions.
