### ISSUE TITLE
Monoid instance?

### ISSUE THREAD

**Issue by mwotton** [ekmett/semigroups#67]
Is there a reason a Monoid instance isn't supplied? standard list concatenation seems to work fine with the laws.

**Comment by RyanGlScott** [comment]
I assume you're referring to `NonEmpty`? What would a law-abiding `mempty` implementation be?

**Comment by mwotton** [comment]
blah. that makes sense - sorry, wasn't thinking. Hrm. is there a smaller thing I can rely on that can always do concatenation without mempty?

**Comment by RyanGlScott** [comment]
Yes, it's called `Semigroup` ;)

**Comment by mwotton** [comment]
ah, comes the dawn - i just need to import <> from a different place. oops. :) Thank you!
