### ISSUE TITLE
No instance for (Semigroup Builder)

### ISSUE THREAD

**Issue by lpsmith** [ekmett/semigroups#70]
I'm guessing that the merge in #68 is responsible for this [build error in postgresql-simple for GHC 7.8](https://travis-ci.org/lpsmith/postgresql-simple/jobs/140877553).

Curiously,  the [postgresql-simple build for GHC 7.6](https://travis-ci.org/lpsmith/postgresql-simple/jobs/140877551) went off without a hitch.

@RyanGlScott

**Comment by RyanGlScott** [comment]
I believe this is an old `cabal-install` bug rearing its head. I was able to reproduce the issue with `cabal-install-1.18.0.2` (the one used in your failing Travis CI build), but not `cabal-install-1.18.1.3`. Here's what I get when attempting `cabal install --only-dependencies --enable-tests -v3 --dry-run` with `cabal-install-1.18.0.2`:

```
In order, the following would be installed:
...
semigroups-0.18.2 -bytestring (new package)
```

And with `cabal-install-1.18.1.3`:

```
In order, the following would be installed:
...
semigroups-0.18.2 -bytestring-builder (new package)
```

Is it possible to use a later version of `cabal-install` in your Travis builds?

**Comment by hvr** [comment]
@lpsmith I'd happily contribute a `cabal new-build` based .travis script covering as many major GHC versions as possible if you're interested... :-)

**Comment by lpsmith** [comment]
I know very little about travis,  and have just started trying to dig into it a bit.  @hvr,  if you'd like to fix my .travis.yml,  by all means,  be my guest :)

**Comment by RyanGlScott** [comment]
@lpsmith, is this still an issue with your current [`.travis.yml`](https://github.com/lpsmith/postgresql-simple/blob/d39d23fc1cd24a1c49b7b93cc5ec16a0fc101014/.travis.yml)?

**Comment by lpsmith** [comment]
@RyanGlScott  Its working well enough.   It did take some tweaking to add postgres and I ended up removing the sdist stuff because my process is a little funky.
