### ISSUE TITLE
Data.List.NonEmpty.singleton?

### ISSUE THREAD

**Issue by NerdGGuy** [ekmett/semigroups#75]
Need a better name for the fromList version?

Data.List.NonEmpty.singleton :: a -> NonEmpty a
Data.List.NonEmpty.singletonWithList :: a -> [a] -> NonEmpty a

**Comment by NerdGGuy** [comment]
Hmm, I didn't realize Data.List didn't have a singleton function. Maybe we can close this. I was in a Data.Map headspace.

**Comment by RyanGlScott** [comment]
Note that `Data.List.NonEmpty` is in `base` now, and this library's version of `Data.List.NonEmpty` only exists to mirror changes to the `base` version for the benefit of older GHC versions. If you wish to propose this change be made to `base`, I recommend you file it as a proposal to libraries@haskell.org first, so we can get it into `base`.
