### ISSUE TITLE
Appending lists to NonEmpty 

### ISSUE THREAD

**Issue by alexanderkjeldaas** [ekmett/semigroups#79]
Seems like there should be functions for appending a list to a NonEmpty.

`[a] -> NonEmpty a -> NonEmpty a`

and

`NonEmpty a -> [a] -> NonEmpty a`

without going through Maybe.

**Comment by RyanGlScott** [comment]
Note that `Data.List.NonEmpty` is in `base` now, and this library's version of `Data.List.NonEmpty` only exists to mirror changes to the `base` version for the benefit of older GHC versions. If you wish to propose this change be made to `base`, I recommend you file it as a proposal to libraries@haskell.org first, so we can get it into `base`.
