### ISSUE TITLE
redundant `pred` in `stimes`

### ISSUE THREAD

**Issue by hvr** [ekmett/semigroups#83]
It was pointed out in https://ghc.haskell.org/trac/ghc/ticket/14439

that there's a redundant `pred` even though `y` is known to be `odd`:

```hs
  stimes :: Integral b => b -> a -> a
  stimes y0 x0
    | y0 <= 0   = error "stimes: positive multiplier expected"
    | otherwise = f x0 y0
    where
      f x y
        | even y = f (x <> x) (y `quot` 2)
        | y == 1 = x
        | otherwise = g (x <> x) (pred y  `quot` 2) x
      g x y z
        | even y = g (x <> x) (y `quot` 2) z
        | y == 1 = x <> z
        | otherwise = g (x <> x) (pred y `quot` 2) (x <> z)
  {-# INLINE stimes #-}
```

@ekmett  do you agree, or is there some subtle reason for why you made `y` even before dividing by two?

**Comment by ekmett** [comment]
Reasoning seems to work. Amusing that this issue lasted this long. Didn't Lennart write the original 20 years ago or something?

**Comment by hvr** [comment]
Maybe he just wanted the code to be faithful to the mathematical notation you find everywhere, which tries to avoid relying on the truncating property of integer division...

**Comment by RyanGlScott** [comment]
The redundant `pred`s have been removed in `base` in [commit eb5a40cea6c64f5300c7697231cb0ede2c554388](http://git.haskell.org/ghc.git/commit/eb5a40cea6c64f5300c7697231cb0ede2c554388), and I've backported it to `semigroups` in 8b6cd2577ea3075827528fde9af68a193263d550.
