### ISSUE TITLE
Data.Semigroup from this package and Data.Semigroup from base have subtly different APIs

### ISSUE THREAD

**Issue by RyanGlScott** [ekmett/semigroups#86]
Now that the SMP has completed, it's time to face an annoying issue: the `Data.Semigroup` module backported in this library is perniciously different from the one provided in `base`. In particular, the `Semigroup` class defined in this library has a default implementation for `(<>)` in terms of `mappend`:

https://github.com/ekmett/semigroups/blob/34c45776b89434267a22d9427e6bc776c96a9a13/src-ghc7/Data/Semigroup.hs#L215-L219

The `Semigroup` in `base`, however, does not. This is a subtle difference, but one that has bitten in practice. See for instance, https://github.com/hedgehogqa/haskell-hedgehog/issues/141.

If we want to make the two libraries uniform, it seems like we ought to rip out this default implementation. However, that might break other libraries that currently rely this default implementation. I would argue that the pain would be worth it (especially since folks are going to have to do this anyway to upgrade to GHC 8.4), but it would require a breaking change in `semigroups` itself.

**Comment by RyanGlScott** [comment]
Another inconsistency is that `Data.Semigroup` from `semigroups` currently reexports `Monoid(..)`, but the one in `base` does not. I'm more on the fence about changing this, since the `Data.Semigroup` from `base` also reexported `Monoid(..)` up until GHC 8.4, so if we changed this in `semigroups`, then we'd have an odd scenario where `Data.Semigroup` only reexports `Monoid(..)` on two particular versions of GHC (8.0 and 8.2).

**Comment by hvr** [comment]
Fwiw, I've been thinking for a while, that if `Semigroup` (and `Monoid`) is to have a defaultSignature method, it ought rather be doing the "obvious" `Generics`-based derivation, in order to support AnyClass deriving convenience... :-)

So this problem affects you mostly if you develop against GHC < 8 + `semigroups`, and then blindly assume that the same semantics hold with GHC >= 8? The other way round seems safe, as when something works in GHC 8.4, then it will work for GHC < 8 + `semigroups` as intended?

**Comment by RyanGlScott** [comment]
> The other way round seems safe, as when something works in GHC 8.4, then it will work for GHC < 8 + `semigroups` as intended?

I suppose. It's still a bit of a nasty surprise to upgrade your library to support 8.4 for the first time only to discover that your `Semigroup` instances now error at runtime. I'd argue that we should eliminate that surprise if possible.

**Comment by phadej** [comment]
The next version is major, so maybe do this for `semigroups-0.19` too?

**Comment by ekmett** [comment]
Sounds good to me.
