### ISSUE TITLE
Backport Lift instance for NonEmpty

### ISSUE THREAD

**Issue by RyanGlScott** [ekmett/semigroups#89]
`template-haskell-2.15` (GHC 8.8) will [debut](http://git.haskell.org/ghc.git/commit/47875bd4d79ca633b589e63e320aa5a5c631d096) a `Lift` instance for `NonEmpty`. We should backport it in this library as well (behind a `template-haskell` Cabal flag).

**Comment by phadej** [comment]
Note, we can write `Lift` instance without requiring `TemplateHaskell` language extension.

**Comment by RyanGlScott** [comment]
Sure. My comment about guarding the instance behind a `Cabal` flag wasn't out of concern for having to enable the language extension (which we don't need to do anyway), but rather to make it consistent with other instances in `semigroups` that require importing things from other libraries ([here's](https://github.com/ekmett/semigroups/blob/c2f7ae6f42f0416bd5fae385f8a3c9232f355d94/semigroups.cabal#L33-L115) the current laundry list of them).
